// Generated by ProbeStack CodeGen. Safe to edit.
package com.probestack.forgestudio.design.service;

import com.probestack.forgestudio.design.domain.repository.ApplyRecommendationRequestDomainRepository;
import com.probestack.forgestudio.design.logging.BusinessOperationLogger;
import com.probestack.forgestudio.design.model.AnalyzeQueryRequest;
import com.probestack.forgestudio.design.model.ApplyRecommendationRequest;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentMatchers;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

class QueriesServiceTest {

    private final ApplyRecommendationRequestDomainRepository repository = mock(ApplyRecommendationRequestDomainRepository.class);
    private final QueriesService service = new QueriesService(repository, mock(BusinessOperationLogger.class));

    private static ApplyRecommendationRequest entity() {
        ApplyRecommendationRequest entity = new ApplyRecommendationRequest();
        return entity;
    }

    @Test
    void analyzeQuery_isNotImplementedUntilBusinessLogicExists() {
        assertThrows(RuntimeException.class, () -> service.analyzeQuery(new AnalyzeQueryRequest()));
    }

    @Test
    void applyRecommendation_isNotImplementedUntilBusinessLogicExists() {
        assertThrows(RuntimeException.class, () -> service.applyRecommendation(UUID.fromString("00000000-0000-0000-0000-000000000001"), entity()));
    }

    @Test
    void getQueryAnalysis_returnsTheEntityWhenItExists() {
        when(repository.findById(ArgumentMatchers.anyString())).thenReturn(Optional.of(entity()));
        var response = service.getQueryAnalysis(UUID.fromString("00000000-0000-0000-0000-000000000001"), true);
        assertTrue(response.getStatusCode().is2xxSuccessful());
        assertNotNull(response.getBody());
    }

    @Test
    void getQueryAnalysis_failsWhenTheEntityDoesNotExist() {
        when(repository.findById(ArgumentMatchers.anyString())).thenReturn(Optional.empty());
        assertThrows(RuntimeException.class, () -> service.getQueryAnalysis(UUID.fromString("00000000-0000-0000-0000-000000000001"), true));
    }

    @Test
    void listSlowQueries_returnsEveryEntity() {
        when(repository.findAll()).thenReturn(List.of(entity()));
        var response = service.listSlowQueries("id-1", 1, 1, "id-1", "id-1", "id-1", 1, 1);
        assertTrue(response.getStatusCode().is2xxSuccessful());
        assertNotNull(response.getBody());
    }

}
