package com.probestack.forgestudio.design.service;

import com.probestack.forgestudio.design.domain.repository.ApplyRecommendationRequestDomainRepository;
import com.probestack.forgestudio.design.exception.ApiException;
import com.probestack.forgestudio.design.logging.BusinessOperationEvent;
import com.probestack.forgestudio.design.logging.BusinessOperationLogger;
import com.probestack.forgestudio.design.model.AnalyzeQueryRequest;
import com.probestack.forgestudio.design.model.ApplyRecommendationRequest;
import com.probestack.forgestudio.design.model.ListSlowQueries200Response;
import com.probestack.forgestudio.design.model.OptimizationAction;
import com.probestack.forgestudio.design.model.QueryAnalysis;
import com.probestack.forgestudio.design.model.QueryAnalysisAntiPatternsInner;
import com.probestack.forgestudio.design.model.SlowQuery;
import java.lang.reflect.Method;
import java.util.Collections;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import java.util.stream.Collectors;
import org.springframework.beans.BeanUtils;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;

/**
 * Service layer for ApplyRecommendationRequest operations.
 *
 * <p>This service depends on a persistence-neutral domain repository port.</p>
 *
 * @author Generated by ProbeStack CodeGen
 * <p>Note: Mapper methods use BeanUtils.copyProperties() for automatic field mapping.</p>
 */
@Service
public class QueriesService {
    private final ApplyRecommendationRequestDomainRepository applyRecommendationRequestDomainRepository;

    private final BusinessOperationLogger businessOperationLogger;

    public QueriesService(
            ApplyRecommendationRequestDomainRepository applyRecommendationRequestDomainRepository,
            BusinessOperationLogger businessOperationLogger) {
        this.applyRecommendationRequestDomainRepository = applyRecommendationRequestDomainRepository;
        this.businessOperationLogger = businessOperationLogger;
    }

    public ResponseEntity<QueryAnalysis> analyzeQuery(AnalyzeQueryRequest analyzeQueryRequest) {
        long businessStartedAt = System.nanoTime();
        try {
            // TODO: Implement custom business logic
            // Available repository methods:
            //   - save(entity) - Create or update
            //   - findById(id) - Find by ID
            //   - findAll() - Get all entities
            //   - existsById(id) - Check if exists
            //   - deleteById(id) - Delete by ID
            //   - count() - Count all entities
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("analyzeQuery")
                            .resource("ApplyRecommendationRequest")
                            .action("UNKNOWN")
                            .status("NOT_IMPLEMENTED")
                            .repository("ApplyRecommendationRequestRepository")
                            .collection("query_lens_queries")
                            .durationMs(businessDurationMs(businessStartedAt))
                            .build());
            throw ApiException.notImplemented("Generated operation analyzeQuery requires custom business logic");
        } catch (RuntimeException exception) {
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("analyzeQuery")
                            .resource("ApplyRecommendationRequest")
                            .action("UNKNOWN")
                            .status("FAILED")
                            .repository("ApplyRecommendationRequestDomainRepository")
                            .collection("query_lens_queries")
                            .durationMs(businessDurationMs(businessStartedAt))
                            .errorCode("business_operation_failed")
                            .errorMessage(exception.getMessage())
                            .build(), exception);
            throw exception;
        }
    }

    public ResponseEntity<OptimizationAction> applyRecommendation(UUID recommendationId,
            ApplyRecommendationRequest applyRecommendationRequest) {
        long businessStartedAt = System.nanoTime();
        try {
            // TODO: Implement custom business logic
            // Available repository methods:
            //   - save(entity) - Create or update
            //   - findById(id) - Find by ID
            //   - findAll() - Get all entities
            //   - existsById(id) - Check if exists
            //   - deleteById(id) - Delete by ID
            //   - count() - Count all entities
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("applyRecommendation")
                            .resource("ApplyRecommendationRequest")
                            .action("UNKNOWN")
                            .status("NOT_IMPLEMENTED")
                            .repository("ApplyRecommendationRequestRepository")
                            .collection("query_lens_queries")
                            .durationMs(businessDurationMs(businessStartedAt))
                            .build());
            throw ApiException.notImplemented("Generated operation applyRecommendation requires custom business logic");
        } catch (RuntimeException exception) {
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("applyRecommendation")
                            .resource("ApplyRecommendationRequest")
                            .action("UNKNOWN")
                            .status("FAILED")
                            .repository("ApplyRecommendationRequestDomainRepository")
                            .collection("query_lens_queries")
                            .durationMs(businessDurationMs(businessStartedAt))
                            .errorCode("business_operation_failed")
                            .errorMessage(exception.getMessage())
                            .build(), exception);
            throw exception;
        }
    }

    public ResponseEntity<QueryAnalysis> getQueryAnalysis(UUID analysisId,
            Boolean includeExplainPlan) {
        long businessStartedAt = System.nanoTime();
        try {
            // Retrieve entity by ID from database
            String repositoryId = toRepositoryId(analysisId);
            Optional<ApplyRecommendationRequest> entity = applyRecommendationRequestDomainRepository.findById(repositoryId);
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("getQueryAnalysis")
                            .resource("ApplyRecommendationRequest")
                            .action("READ")
                            .status("SUCCESS")
                            .repository("ApplyRecommendationRequestDomainRepository")
                            .collection("query_lens_queries")
                            .documentId(repositoryId)
                            .recordCount(entity.isPresent() ? 1 : 0)
                            .durationMs(businessDurationMs(businessStartedAt))
                            .build());
            // Map entity to response DTO
            return entity.map(this::mapToQueryAnalysis).map(ResponseEntity::ok).orElseThrow(() -> ApiException.notFound("ApplyRecommendationRequest", repositoryId));
        } catch (RuntimeException exception) {
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("getQueryAnalysis")
                            .resource("ApplyRecommendationRequest")
                            .action("READ")
                            .status("FAILED")
                            .repository("ApplyRecommendationRequestDomainRepository")
                            .collection("query_lens_queries")
                            .durationMs(businessDurationMs(businessStartedAt))
                            .errorCode("database_read_failed")
                            .errorMessage(exception.getMessage())
                            .build(), exception);
            throw exception;
        }
    }

    public ResponseEntity<ListSlowQueries200Response> listSlowQueries(String databaseId,
            Integer minLatencyMs, Integer minCallFrequency, String environment, String orderBy,
            String window, Integer page, Integer size) {
        long businessStartedAt = System.nanoTime();
        try {
            // Retrieve all entities from database
            List<ApplyRecommendationRequest> entities = applyRecommendationRequestDomainRepository.findAll();
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("listSlowQueries")
                            .resource("ApplyRecommendationRequest")
                            .action("READ")
                            .status("SUCCESS")
                            .repository("ApplyRecommendationRequestDomainRepository")
                            .collection("query_lens_queries")
                            .recordCount(entities.size())
                            .durationMs(businessDurationMs(businessStartedAt))
                            .build());
            // Step 1: Map persisted entities to the OpenAPI wrapper item DTOs
            List<SlowQuery> responses = entities.stream().map(this::mapToSlowQuery).collect(Collectors.toList());
            // Step 2: Create the OpenAPI list wrapper and populate its list property
            ListSlowQueries200Response response = new ListSlowQueries200Response();
            response.setContent(responses);
            // Step 3: Return the wrapper response required by the API contract
            return ResponseEntity.ok(response);
        } catch (RuntimeException exception) {
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("listSlowQueries")
                            .resource("ApplyRecommendationRequest")
                            .action("READ")
                            .status("FAILED")
                            .repository("ApplyRecommendationRequestDomainRepository")
                            .collection("query_lens_queries")
                            .durationMs(businessDurationMs(businessStartedAt))
                            .errorCode("database_read_failed")
                            .errorMessage(exception.getMessage())
                            .build(), exception);
            throw exception;
        }
    }

    /**
     * Converts OpenAPI path IDs to the repository ID type.
     */
    private String toRepositoryId(Object id) {
        if (id == null) {
            return null;
        }
        return id.toString();
    }

    /**
     * Assigns a Mongo document ID when the generated model does not have one yet.
     */
    private void ensureEntityId(Object entity) {
        if (entity == null) {
            return;
        }
        try {
            Method getter = entity.getClass().getMethod("getId");
            Object currentId = getter.invoke(entity);
            if (currentId == null || currentId.toString().isBlank()) {
                setEntityId(entity, UUID.randomUUID().toString());
            }
        } catch (Exception ignored) {
            // Generated models are enhanced with getId/setId; ignore if custom code removed them.
        }
    }

    private void setEntityId(Object entity, String id) {
        if (entity == null || id == null) {
            return;
        }
        try {
            Method setter = entity.getClass().getMethod("setId", String.class);
            setter.invoke(entity, id);
        } catch (Exception ignored) {
            // Generated models are enhanced with setId; ignore if custom code removed it.
        }
    }

    private String getEntityId(Object entity) {
        if (entity == null) {
            return null;
        }
        try {
            Method getter = entity.getClass().getMethod("getId");
            Object value = getter.invoke(entity);
            return value != null ? value.toString() : null;
        } catch (Exception ignored) {
            return null;
        }
    }

    private void copyGeneratedId(Object entity, Object response) {
        String id = getEntityId(entity);
        if (id == null || response == null) {
            return;
        }
        for (Method method : response.getClass().getMethods()) {
            if (method.getName().startsWith("set") && method.getName().endsWith("Id") && method.getParameterCount() == 1 && method.getParameterTypes()[0].equals(String.class)) {
                try {
                    method.invoke(response, id);
                    return;
                } catch (Exception ignored) {
                    // Try the next compatible ID setter.
                }
            }
        }
    }

    /**
     * Creates an empty response wrapper for list/search endpoints.
     */
    private <T> T emptyResponse(Class<T> responseType) {
        try {
            T response = responseType.getDeclaredConstructor().newInstance();
            for (Method method : responseType.getMethods()) {
                if (method.getName().startsWith("set") && method.getParameterCount() == 1 && List.class.isAssignableFrom(method.getParameterTypes()[0])) {
                    method.invoke(response, Collections.emptyList());
                }
            }
            return response;
        } catch (Exception ignored) {
            return null;
        }
    }

    /**
     * Calculates elapsed milliseconds for generated business operation logs.
     */
    private Long businessDurationMs(long startedAt) {
        return (System.nanoTime() - startedAt) / 1_000_000L;
    }

    /**
     * Maps ApplyRecommendationRequest entity to OptimizationAction response DTO.
     *
     * <p>Uses Spring BeanUtils.copyProperties() to automatically copy matching fields.</p>
     *
     * @param entity the entity to map
     * @return mapped response DTO
     */
    private OptimizationAction mapToOptimizationAction(ApplyRecommendationRequest entity) {
        // Create new response object
        OptimizationAction response = new OptimizationAction();
        // Copy matching properties from entity to response
        BeanUtils.copyProperties(entity, response);
        copyGeneratedId(entity, response);
        // 
        // TODO: Add custom field mappings here if needed
        // Example:
        //   response.setCustomField(entity.getSourceField());
        //   response.setMessage("Success");
        // 
        return response;
    }

    /**
     * Maps ApplyRecommendationRequest entity to SlowQuery response DTO.
     *
     * <p>Uses Spring BeanUtils.copyProperties() to automatically copy matching fields.</p>
     *
     * @param entity the entity to map
     * @return mapped response DTO
     */
    private SlowQuery mapToSlowQuery(ApplyRecommendationRequest entity) {
        // Create new response object
        SlowQuery response = new SlowQuery();
        // Copy matching properties from entity to response
        BeanUtils.copyProperties(entity, response);
        copyGeneratedId(entity, response);
        // 
        // TODO: Add custom field mappings here if needed
        // Example:
        //   response.setCustomField(entity.getSourceField());
        //   response.setMessage("Success");
        // 
        return response;
    }

    /**
     * Maps ApplyRecommendationRequest entity to QueryAnalysisAntiPatternsInner response DTO.
     *
     * <p>Uses Spring BeanUtils.copyProperties() to automatically copy matching fields.</p>
     *
     * @param entity the entity to map
     * @return mapped response DTO
     */
    private QueryAnalysisAntiPatternsInner mapToQueryAnalysisAntiPatternsInner(
            ApplyRecommendationRequest entity) {
        // Create new response object
        QueryAnalysisAntiPatternsInner response = new QueryAnalysisAntiPatternsInner();
        // Copy matching properties from entity to response
        BeanUtils.copyProperties(entity, response);
        copyGeneratedId(entity, response);
        // 
        // TODO: Add custom field mappings here if needed
        // Example:
        //   response.setCustomField(entity.getSourceField());
        //   response.setMessage("Success");
        // 
        return response;
    }

    /**
     * Maps ApplyRecommendationRequest entity to QueryAnalysis response DTO.
     *
     * <p>Uses Spring BeanUtils.copyProperties() to automatically copy matching fields.</p>
     *
     * @param entity the entity to map
     * @return mapped response DTO
     */
    private QueryAnalysis mapToQueryAnalysis(ApplyRecommendationRequest entity) {
        // Create new response object
        QueryAnalysis response = new QueryAnalysis();
        // Copy matching properties from entity to response
        BeanUtils.copyProperties(entity, response);
        copyGeneratedId(entity, response);
        // 
        // TODO: Add custom field mappings here if needed
        // Example:
        //   response.setCustomField(entity.getSourceField());
        //   response.setMessage("Success");
        // 
        return response;
    }
}
