// Generated by ProbeStack CodeGen. Safe to edit.
package com.probestack.forgestudio.design.api;

import com.probestack.forgestudio.design.advice.GlobalExceptionHandler;
import com.probestack.forgestudio.design.config.validation.ValidationProperties;
import com.probestack.forgestudio.design.domain.repository.ApplyRecommendationRequestDomainRepository;
import com.probestack.forgestudio.design.logging.BusinessOperationLogger;
import com.probestack.forgestudio.design.model.ApplyRecommendationRequest;
import com.probestack.forgestudio.design.service.QueriesService;
import com.probestack.forgestudio.design.validation.GeneratedRequestValidator;
import jakarta.validation.Validation;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentMatchers;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;

import static org.mockito.Mockito.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.request;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

class QueriesApiControllerIntegrationTest {

    private final ApplyRecommendationRequestDomainRepository repository = mock(ApplyRecommendationRequestDomainRepository.class);
    private MockMvc mockMvc;

    private static ApplyRecommendationRequest entity() {
        ApplyRecommendationRequest entity = new ApplyRecommendationRequest();
        return entity;
    }

    @BeforeEach
    void setUp() {
        QueriesService service = new QueriesService(repository, mock(BusinessOperationLogger.class));
        ValidationProperties properties = new ValidationProperties();
        properties.setEnabled(true);
        GeneratedRequestValidator validator = new GeneratedRequestValidator(properties,
                Validation.buildDefaultValidatorFactory().getValidator());
        QueriesApiController controller = new QueriesApiController(service, validator);
        mockMvc = MockMvcBuilders.standaloneSetup(controller)
                .setControllerAdvice(new GlobalExceptionHandler())
                .addPlaceholderValue("openapi.queryLens.base-path", "/v1")
                .build();
    }

    @Test
    void analyzeQuery_isNotImplementedUntilBusinessLogicExists() throws Exception {
        mockMvc.perform(request(HttpMethod.POST, "/v1/analyze")
                .contentType(MediaType.APPLICATION_JSON)
                .content("{\"databaseId\":\"payment-db-prod\",\"querySource\":\"INLINE_SQL\",\"inlineSql\":\"SELECT * FROM orders WHERE customer_id = 12345 AND status = 'PENDING' ORDER BY created_at DESC LIMIT 100;\",\"slowQueryId\":\"sq-abc-123\",\"parameters\":{\"customer_id\":12345,\"status\":\"PENDING\"},\"includeExplainAnalyze\":false,\"environment\":\"PRODUCTION\",\"applicationContext\":{\"service\":\"order-service\",\"endpoint\":\"GET /api/v1/orders\",\"p99LatencyMs\":847,\"callFrequencyPerMinute\":450}}"))
                .andExpect(status().isNotImplemented());
    }

    @Test
    void getQueryAnalysis_returnsTheEntity() throws Exception {
        when(repository.findById(ArgumentMatchers.anyString())).thenReturn(Optional.of(entity()));
        mockMvc.perform(request(HttpMethod.GET, "/v1/analyses/{analysisId}", "00000000-0000-0000-0000-000000000001"))
                .andExpect(status().is2xxSuccessful());
    }

    @Test
    void getQueryAnalysis_isNotFoundWhenTheEntityDoesNotExist() throws Exception {
        when(repository.findById(ArgumentMatchers.anyString())).thenReturn(Optional.empty());
        mockMvc.perform(request(HttpMethod.GET, "/v1/analyses/{analysisId}", "00000000-0000-0000-0000-000000000001"))
                .andExpect(status().isNotFound());
    }

    @Test
    void listSlowQueries_returnsEveryEntity() throws Exception {
        when(repository.findAll()).thenReturn(List.of(entity()));
        mockMvc.perform(request(HttpMethod.GET, "/v1/slow-queries"))
                .andExpect(status().is2xxSuccessful());
    }

    @Test
    void applyRecommendation_isNotImplementedUntilBusinessLogicExists() throws Exception {
        mockMvc.perform(request(HttpMethod.POST, "/v1/recommendations/{recommendationId}/apply", "00000000-0000-0000-0000-000000000001")
                .contentType(MediaType.APPLICATION_JSON)
                .content("{\"mode\":\"CANARY_ON_REPLICA\",\"reason\":\"Index on orders(customer_id, status) — canary on read replica first.\",\"scheduledAt\":1790560800000,\"revertWindowMinutes\":60,\"notifyChannels\":[\"SLACK\"]}"))
                .andExpect(status().isNotImplemented());
    }

}
