// Generated by ProbeStack CodeGen. Safe to edit.
package com.probestack.forgestudio.design.persistence.mongodb.adapter;

import com.probestack.forgestudio.design.model.ApplyRecommendationRequest;
import com.probestack.forgestudio.design.persistence.mongodb.document.ApplyRecommendationRequestDocument;
import com.probestack.forgestudio.design.persistence.mongodb.repository.ApplyRecommendationRequestMongoRepository;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;
import org.mockito.ArgumentMatchers;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

class ApplyRecommendationRequestMongoPersistenceAdapterTest {

    private final ApplyRecommendationRequestMongoRepository repository = mock(ApplyRecommendationRequestMongoRepository.class);
    private final ApplyRecommendationRequestMongoPersistenceAdapter adapter = new ApplyRecommendationRequestMongoPersistenceAdapter(repository);

    private static ApplyRecommendationRequest domain() {
        ApplyRecommendationRequest domain = new ApplyRecommendationRequest();
        return domain;
    }

    private static ApplyRecommendationRequestDocument stored() {
        ApplyRecommendationRequestDocument stored = new ApplyRecommendationRequestDocument();
        return stored;
    }

    @Test
    void save_mapsToThePersistenceModelAndBack() {
        when(repository.save(ArgumentMatchers.any(ApplyRecommendationRequestDocument.class))).thenAnswer(invocation -> invocation.getArgument(0));
        ApplyRecommendationRequest saved = adapter.save(domain());
        ArgumentCaptor<ApplyRecommendationRequestDocument> captor = ArgumentCaptor.forClass(ApplyRecommendationRequestDocument.class);
        verify(repository).save(captor.capture());
        assertNotNull(saved);
    }

    @Test
    void findById_mapsAStoredEntityToTheDomainModel() {
        when(repository.findById("id-1")).thenReturn(Optional.of(stored()));
        Optional<ApplyRecommendationRequest> found = adapter.findById("id-1");
        assertTrue(found.isPresent());
    }

    @Test
    void findById_isEmptyWhenNothingIsStored() {
        when(repository.findById("id-1")).thenReturn(Optional.empty());
        assertTrue(adapter.findById("id-1").isEmpty());
    }

    @Test
    void findAll_mapsEveryStoredEntity() {
        when(repository.findAll()).thenReturn(List.of(stored()));
        List<ApplyRecommendationRequest> all = adapter.findAll();
        assertEquals(1, all.size());
    }

    @Test
    void existsById_delegatesToTheRepository() {
        when(repository.existsById("id-1")).thenReturn(true);
        assertTrue(adapter.existsById("id-1"));
    }

    @Test
    void deleteById_delegatesToTheRepository() {
        adapter.deleteById("id-1");
        verify(repository).deleteById("id-1");
    }

    @Test
    void count_delegatesToTheRepository() {
        when(repository.count()).thenReturn(3L);
        assertEquals(3L, adapter.count());
    }

}
